import { beforeEach, describe, test } from "vitest";
import { expect } from "chai";
import { Board } from "../src/Board.mjs";
import { Tetromino } from "../src/Tetromino.mjs";

describe('Tetrominoes move', () => {
  let board
  beforeEach(() => {
    board = new Board(10, 6)
  })

  test('to the left', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveLeft()

    expect(board.toString()).to.equalShape(
      `..TTT.....
       ...T......
       ..........
       ..........
       ..........
       ..........`
    )
  })

  test('to the right', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveRight()

    expect(board.toString()).to.equalShape(
      `....TTT...
       .....T....
       ..........
       ..........
       ..........
       ..........`
    )
  })

  test('down', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveDown()

    expect(board.toString()).to.equalShape(
      `..........
       ...TTT....
       ....T.....
       ..........
       ..........
       ..........`
    )
  })
})

describe('Tetrominoes cannot move beyond the board', () => {
  let board
  beforeEach(() => {
    board = new Board(10, 6)
  })

  test('to the left', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveLeft()
    board.moveLeft()
    board.moveLeft() // edge
    expect(board.toString()).to.equalShape(
      `TTT.......
       .T........
       ..........
       ..........
       ..........
       ..........`
    )

    board.moveLeft() // stop at edge
    expect(board.toString()).to.equalShape(
      `TTT.......
       .T........
       ..........
       ..........
       ..........
       ..........`
    )
  })

  test('to the right', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveRight()
    board.moveRight()
    board.moveRight()
    board.moveRight() // edge
    expect(board.toString()).to.equalShape(
      `.......TTT
       ........T.
       ..........
       ..........
       ..........
       ..........`
    )

    board.moveRight() // stop at edge
    expect(board.toString()).to.equalShape(
      `.......TTT
       ........T.
       ..........
       ..........
       ..........
       ..........`
    )
  })

  test('to the bottom', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveDown()
    board.moveDown()
    board.moveDown()
    board.moveDown() // bottom
    expect(board.hasFalling(), "the tetromino should still be moving").to.be.true;
    board.moveDown() // stop at bottom

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ..........
       ..........
       ...TTT....
       ....T.....`
    )

    expect(board.hasFalling(), "the tetromino should stop moving").to.be.false;
  })
})

describe('Tetrominoes cannot move through other blocks', () => {
  let board
  beforeEach(() => {
    board = new Board(10, 6)
    board.setState(
      `..........
       ..........
       ....I.....
       ....I.....
       ....I.....
       ....I.....`
    )
  })

  test('to the left', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveRight()
    board.moveRight()
    board.moveDown()
    board.moveDown() // next to I

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ....ITTT..
       ....I.T...
       ....I.....
       ....I.....`
    )

    board.moveLeft() // should not move
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       ....ITTT..
       ....I.T...
       ....I.....
       ....I.....`
    )
  })

  test('to the right', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA)
    board.moveLeft()
    board.moveLeft()
    board.moveDown()
    board.moveDown() // next to I

    expect(board.toString()).to.equalShape(
      `..........
       ..........
       .TTTI.....
       ..T.I.....
       ....I.....
       ....I.....`
    )

    board.moveRight() // should not move
    expect(board.toString()).to.equalShape(
      `..........
       ..........
       .TTTI.....
       ..T.I.....
       ....I.....
       ....I.....`
    )
  })

  test('to the bottom', () => {
    board.drop(Tetromino.T_SHAPE_ARIKA) // above I

    expect(board.toString()).to.equalShape(
      `...TTT....
       ....T.....
       ....I.....
       ....I.....
       ....I.....
       ....I.....`
    )
    expect(board.hasFalling(), "the tetromino should still be moving").to.be.true;

    board.moveDown() // should not move
    expect(board.toString()).to.equalShape(
      `...TTT....
       ....T.....
       ....I.....
       ....I.....
       ....I.....
       ....I.....`
    )
    expect(board.hasFalling(), "the tetromino should stop moving").to.be.false;
  })
})